name: Build and Release

on:
    push:
        tags:
            - "v*"

jobs:
    build-and-release:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install build tooling
              run: |
                  python -m pip install --upgrade pip
                  pip install build wheel

            - name: Build distributions
              run: |
                  python -m build
                  ls -lh dist

            - name: Create GitHub Release for this tag
              id: create_release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ github.ref_name }}
              run: |
                  gh release create "$tag" \
                    --repo="$GITHUB_REPOSITORY" \
                    --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                    --generate-notes || true

                  gh release upload "$tag" \
                    --repo="$GITHUB_REPOSITORY" \
                    ./dist/*.whl

            - name: Update permanent index release with all wheels
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  # Create the "index" release if it doesn't exist (idempotent)
                  gh release view index --repo "$GITHUB_REPOSITORY" >/dev/null 2>&1 || \
                    gh release create index \
                      --repo "$GITHUB_REPOSITORY" \
                      --title "index" \
                      --notes "All released wheels for pip/uv --find-links" \
                      --latest=false

                  # Upload current wheels to the index release (overwrite if same filename)
                  gh release upload index \
                    --repo "$GITHUB_REPOSITORY" \
                    ./dist/*.whl \
                    --clobber
